### ISSUE TITLE
KeyError: 'tfds_data_dir'(GANSynth)

### ISSUE THREAD

**Issue by YB-Joe** [magenta/magenta#1800] opened 2020-08-28 11:08 UTC
Hi, I got this error on GANSynth demo colab . How can I resolve it?

![image](https://user-images.githubusercontent.com/43649503/91554417-0a7d2400-e96a-11ea-9905-893c535b196a.png)

**Comment by PRamoneda** [comment] 2020-10-04 21:57
I have the same problem

**Comment by jamesliu** [comment] 2020-10-14 22:44
> I have the same problem

Same here

**Comment by ksunw0209** [comment] 2020-11-12 11:36
Same... Does anybody know how to fix it?

**Comment by adarob** [comment] 2020-11-12 13:48
I cannot reproduce this error. Instead I get a different error: 

`AttributeError: 'PrefetchDataset' object has no attribute 'make_initializable_iterator'`

I will put in a fix for this new error.

**Comment by ksunw0209** [comment] 2020-11-12 13:55
I actually got the error above when I ran the colab demo on GANSynth. So I ran the code in Read.me using my local device which gave me the error in this thread.
Thank you.

**Comment by adarob** [comment] 2020-11-12 13:57
Which line in the README gave you this error?

**Comment by ksunw0209** [comment] 2020-11-12 14:01
`gansynth_generate --ckpt_dir=/path/to/acoustic_only --output_dir=/path/to/output/dir --midi_file=/path/to/file.mid`
I bet it's similar with this one: https://github.com/magenta/magenta/issues/1794
I pip installed gansynth, and it gave me this error.

**Comment by adarob** [comment] 2020-11-12 14:10
@jesseengel FYI

Yes, this is an unfortunate issue where the model restoration requires the train dataset to be loaded. Rather than refactoring this legacy code, I created #1851 a bandaid.

**Comment by ksunw0209** [comment] 2020-11-12 14:20
Aha... thank you. Does the colab demo have to work now? I still get the following error.
`AttributeError: 'PrefetchDataset' object has no attribute 'make_initializable_iterator'`
Plus there is an additional version error.
`ERROR: kfac 0.2.3 has requirement tensorflow-probability==0.8, but you'll have tensorflow-probability 0.11.0 which is incompatible.
ERROR: tensor2tensor 1.15.7 has requirement tensorflow-probability==0.7.0, but you'll have tensorflow-probability 0.11.0 which is incompatible.`

**Comment by adarob** [comment] 2020-11-12 14:24
You can ignore the version error. The Colab will work again once #1850 is in and we push the new pip package. Probably later today.

**Comment by ksunw0209** [comment] 2020-11-12 14:26
Thank you so much:) Keep up the great work! 👍

**Closed** 2020-11-12 19:09 UTC
